CREATE DATABASE TEST
GO

USE TEST
GO

CREATE TABLE Usuario
(
    Id INT IDENTITY PRIMARY KEY NOT NULL,
    Nombre NVARCHAR(50) NOT NULL,
    Apellidos NVARCHAR(75) NOT NULL,
    Cumpleaños DATETIME2 NULL,
    IdProvincia TINYINT NOT NULL
)
GO

CREATE TABLE Provincia
(
    Id TINYINT PRIMARY KEY NOT NULL,
    Nombre NVARCHAR(50)
)
GO

ALTER TABLE Usuario
ADD CONSTRAINT FK_Usuario_Provincia FOREIGN KEY (IdProvincia)
REFERENCES Provincia (Id)
GO